# Generated by Django 4.1.4 on 2022-12-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='course',
            field=models.ManyToManyField(to='course.course'),
        ),
    ]
